/* Version information autogenerated by version fragment */
#ifndef captAna_NAME
#define captAna_NAME "captAna"
#define captAna_VERSION "v1"
#define captAna_MAJOR_VERSION 1
#define captAna_MINOR_VERSION 0
#define captAna_PATCH_VERSION 0
#define BEFORE_captAna(v,r,p) ((captAna_MAJOR_VERSION==(v)&&captAna_MINOR_VERSION==(r)&&captAna_PATCH_VERSION<(p))||(captAna_MAJOR_VERSION==(v)&&captAna_MINOR_VERSION<(r))||(captAna_MAJOR_VERSION<(v)))
#define EQUALS_captAna(v,r,p) (captAna_MAJOR_VERSION==(v)&&captAna_MINOR_VERSION==(r)&&captAna_PATCH_VERSION==(p))
#define captAna_COMPILE_DATE "Fri Jan 15 17:30:08 UTC 2016"
#define captAna_COMPILE_HOST "red"
#define captAna_COMPILE_UNAME "Linux red 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 08:24:23 CST 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define captAna_COMPILE_DIR "/home/gold/captain/myProject/captAna/v1/cmt"
#endif
