/* Version information autogenerated by version fragment */
#ifndef captRoot_NAME
#define captRoot_NAME "captRoot"
#define captRoot_VERSION "v1"
#define captRoot_MAJOR_VERSION 1
#define captRoot_MINOR_VERSION 0
#define captRoot_PATCH_VERSION 0
#define BEFORE_captRoot(v,r,p) ((captRoot_MAJOR_VERSION==(v)&&captRoot_MINOR_VERSION==(r)&&captRoot_PATCH_VERSION<(p))||(captRoot_MAJOR_VERSION==(v)&&captRoot_MINOR_VERSION<(r))||(captRoot_MAJOR_VERSION<(v)))
#define EQUALS_captRoot(v,r,p) (captRoot_MAJOR_VERSION==(v)&&captRoot_MINOR_VERSION==(r)&&captRoot_PATCH_VERSION==(p))
#define captRoot_COMPILE_DATE "Sat Jan 16 00:09:23 UTC 2016"
#define captRoot_COMPILE_HOST "red"
#define captRoot_COMPILE_UNAME "Linux red 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 08:24:23 CST 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define captRoot_COMPILE_DIR "/home/gold/captain/myProject/captRoot/cmt"
#endif
